function countingValleys(steps, path) {
    // Write your code here
    let preAlt = 0;
    let altitude = 0;
    let valleyCount = 0;

    for (let i = 0; i < steps; i++) {

        preAlt = altitude;
        if (path[i] === "D") {
            altitude -= 1;
        } else {
            altitude += 1;
        }        


        if (path[i] === "U" && altitude === 0 && preAlt < 0) {
            valleyCount += 1;
        }
    }

    return valleyCount;
}

let len1 = 8;
let str1 = "UDDDUDUU"


let len2 = 1000000;
let str2 = "DDDUDDUUDUDUUUUDUDUDDDDDDUDUDUDDUDUDDUDDUDUDUUDDDDUDUUUUDDDUUDDDUUDUDDDUDUDDUUDDUUDDUDUDDUDUUUUDDDDDUUUUUUDDUUDDDDDUUDUUDUUUDDDDDUUDDUUUDUUDUUDUDDUDDUDUUUUDUDDUDDUUUDUDUUUUUUDDUUUUDDUUDDUDDUDUDUDUDDDDUDUDDDDDDDDUDUDDUUUUDUUDDDDUDUUUUUDUDUDUDUDUUUDDDDDDDDDDDUUDUUDDUDDUDDUDDUUUUDDUUDDUDDUDDDUDDDUUUDUDUDDUUDUDDUDUUUUUUUDUDDDDDDDDDUUUDUDDDDUUDUUUDUUDUUUUUUDDDUDUUDDDDUUUUDDDUDDDUDDDDUDDUUUDUUDDUDDDUUUDUUDUUUDDUDDDDUUUUUDUDDUDDDUUDDUDUUDDDUUUDDDUUDDDDUDDUDDDUDDUUUUDUUUUUDDUDDDDUUDUUDUUUUDDDDUDUUDDUDDUDDDDUUUDDDDUDUDUDUUUDUUDDDDUUDUUUUDDUUDDUDDUUUUDUUDUDUUDDDUUUDUDUUUUDUDDUUDDUUUUDUUUDUDUUUUDDDDUUDUUDUUUDUDUUDDUUUDDDDUUDUDUUDUUDDUDUDUDUUUUUDDDUUUUDUDUDUUDDDDDUDUUDDUDDUDDDDUUDUDUDUUUUUUUDUUUUUUUDUUUUUUUDDDDUUDUUUUDUUDUDUUUDUUDUUDUDDDUUDUDDUDUDDDUDDUUUUDDUDDDDDUDUDDDDUUDUDUUDDDUDDDDUUUUUDDUUDDDDUDDDDDDUUDUUDUUUUDUUUUDUUUDUDDDUDUUUDUUUUDUUUUUUUUUDDDUDDUUUDUDUDDDUDDUUUUDUUDDDUDDUDUDDDUUDDUUUUUUUUUDDDDUUUUDDDUDDDUUUDUDDDDUUUUDUUDUDUUDDUUDDDUDDUUDDUUUUDDDDDUUUUUUDDUUUDDDUDDDUUUUUDDDUDUDDDDDDUUDUDUUDUDUUUUDUUUUUUUU";
let val = countingValleys(len1, str1);
console.log(val)