function countingValleys(steps, path) {
    // Write your code here
    let altitude = 0;
    let valleyCount = 0;
    let preAlt = 0;

    for (let i = 0; i < steps; i++) {
        
        preAlt = altitude;


        if (path[i] === "D") {
            altitude -= 1;
        }

        if (path[i] === "D" && altitude === 0 && i === 0) {

            valleyCount += 1;
            
        }

        if (altitude === -1 &&  preAlt > altitude) {

            valleyCount += 1;
        }


        if (path[i] === "U") {
            altitude += 1;
        }
        

        console.log(path[i]);
        console.log("preALt: " + preAlt);
        console.log("Alt: " + altitude);
        console.log("Count " + valleyCount);
        console.log("-------------");

        
    }

    return valleyCount;
}

let length = 8;
let str = "UDDDUDUU"


let len = 1000000;
let str2 = "DDDUDDUUDUDUUUUDUDUDDDDDDUDUDUDDUDUDDUDDUDUDUUDDDDUDUUUUDDDUUDDDUUDUDDDUDUDDUUDDUUDDUDUDDUDUUUUDDDDDUUUUUUDDUUDDDDDUUDUUDUUUDDDDDUUDDUUUDUUDUUDUDDUDDUDUUUUDUDDUDDUUUDUDUUUUUUDDUUUUDDUUDDUDDUDUDUDUDDDDUDUDDDDDDDDUDUDDUUUUDUUDDDDUDUUUUUDUDUDUDUDUUUDDDDDDDDDDDUUDUUDDUDDUDDUDDUUUUDDUUDDUDDUDDDUDDDUUUDUDUDDUUDUDDUDUUUUUUUDUDDDDDDDDDUUUDUDDDDUUDUUUDUUDUUUUUUDDDUDUUDDDDUUUUDDDUDDDUDDDDUDDUUUDUUDDUDDDUUUDUUDUUUDDUDDDDUUUUUDUDDUDDDUUDDUDUUDDDUUUDDDUUDDDDUDDUDDDUDDUUUUDUUUUUDDUDDDDUUDUUDUUUUDDDDUDUUDDUDDUDDDDUUUDDDDUDUDUDUUUDUUDDDDUUDUUUUDDUUDDUDDUUUUDUUDUDUUDDDUUUDUDUUUUDUDDUUDDUUUUDUUUDUDUUUUDDDDUUDUUDUUUDUDUUDDUUUDDDDUUDUDUUDUUDDUDUDUDUUUUUDDDUUUUDUDUDUUDDDDDUDUUDDUDDUDDDDUUDUDUDUUUUUUUDUUUUUUUDUUUUUUUDDDDUUDUUUUDUUDUDUUUDUUDUUDUDDDUUDUDDUDUDDDUDDUUUUDDUDDDDDUDUDDDDUUDUDUUDDDUDDDDUUUUUDDUUDDDDUDDDDDDUUDUUDUUUUDUUUUDUUUDUDDDUDUUUDUUUUDUUUUUUUUUDDDUDDUUUDUDUDDDUDDUUUUDUUDDDUDDUDUDDDUUDDUUUUUUUUUDDDDUUUUDDDUDDDUUUDUDDDDUUUUDUUDUDUUDDUUDDDUDDUUDDUUUUDDDDDUUUUUUDDUUUDDDUDDDUUUUUDDDUDUDDDDDDUUDUDUUDUDUUUUDUUUUUUUU";
countingValleys(len, str2);